export const ONSWITCH = 'ONSWITCH';
export const GETPOPULARACTORS = 'GETPOPULARACTORS';
export const PLUSMOREACTORS = 'PLUSMOREACTORS';
export const TVINFO = 'TVINFO';
export const MOVIEINFO = 'MOVIEINFO';
export const SAVEPAGEFORACTORS = 'SAVEPAGEFORACTORS';
export const SAVEPAGEFORTVS = 'SAVEPAGEFORTVS';
export const SAVEPAGEFORFILMS = 'SAVEPAGEFORFILMS';
